### ISSUE TITLE
Week 8 is Ready for Review

### ISSUE THREAD

**Issue by arice-student** [arice-student/LabPal#2]
@pawaitemadisoncollege - Week 8 is complete and is ready for review.

**What were your key learning points/takeaways?**
This week, the key learning points were learning about web services and REST, which included exploring a REST service with SoapUI, consuming a REST service with Java and Mapping JSON to a Java Object using RoboPOJOGenerator and Jakson.
**What challenged you?**
The activities and exercises were fairly straight forward this week, however, there will definitely be challenges encountered when implementing an API into my indie project.  I am still not sure what API to use yet though.
**What problems did you solve and what resources did you use to solve them?**
For this week, I was able to complete the videos, activities and exercises using only the content, activities and web sites provided from the course.

**Comment by pawaitemadisoncollege** [comment]
Hi @arice-student - Can you point me to the classes ~and screenshots~ for week 8?  Thanks!

**Comment by arice-student** [comment]
Hi @pawaitemadisoncollege - I just created a new repository and added the classes from week 8 to it.  It can be found here: https://github.com/mad-java-ent-s21/week8-rest-service.  If needed, I can create a new issue within that repository.

**Comment by pawaitemadisoncollege** [comment]
Thanks for putting up the code @arice-student. Things look good there, especially the TODOs around moving the base url and any keys to a property file.  In addition, in a real application, the various methods such as `getPet()` and `getResponse()` would need to be updated to accept a parameter.
